import { runCron } from "@/lib/cron";

/**
 * ★ Cloudflare Worker entry point (custom).
 *
 * OpenNext's build emits `.open-next/worker.js` whose default export is
 * `{ fetch }` (the Next.js request handler) plus any Durable Object classes
 * as named exports. OpenNext has no hook for a cron `scheduled()` handler,
 * so we wrap the generated worker here:
 *   - spread its default export to keep `fetch` (pages, /api/*, /m/[slug]),
 *   - add our `scheduled()` for the every-minute monitor cron,
 *   - `export *` to forward any Durable Object exports (avoids wrangler
 *     "no such Durable Object class is exported" warnings).
 *
 * wrangler.toml's `main` points at THIS file; wrangler bundles it and
 * resolves the import below to the generated artifact at build time.
 */

// @ts-ignore - generated by `opennextjs-cloudflare build`; may be absent pre-build.
import nextWorker from "../.open-next/worker.js";
// @ts-ignore - forward any Durable Object exports from the generated worker.
export * from "../.open-next/worker.js";

interface Env {
  DB: D1Database;
  ASSETS: Fetcher;
  [key: string]: unknown;
}

export default {
  // Inherit fetch (and anything else) from the OpenNext-generated worker.
  ...(nextWorker as ExportedHandler<Env>),

  // ── Cron tick (every minute) -> monitor loop + maintenance steps. ──
  // waitUntil keeps the Worker alive until the tick finishes. runCron is
  // fully guarded (try/catch per step and per monitor) so it always resolves.
  async scheduled(
    _event: ScheduledController,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<void> {
    ctx.waitUntil(
      runCron(env as never)
        .then((r) =>
          console.log(
            `[cron] due=${r.due} checked=${r.checked} failed=${r.failed} alerts=${r.alertsSent}`,
          ),
        )
        .catch((e) => console.error("[cron] fatal", e)),
    );
  },
};
